import { config } from "dotenv";

config();

const {
  PORT = 8080,
  SECRET,
  MONGO_URL,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
  CLIENTE_ID,
  CLIENTE_SECRET,
  CLIENT_REFRESH,
  REDIRECT_URI,
  REFRESH_TOKEN,
} = process.env;

// Cloudinary configuration
const CLOUDINARY = {
  NAME: CLOUDINARY_NAME,
  KEY: CLOUDINARY_KEY,
  SECRET: CLOUDINARY_SECRET,
};

// Google configuration
const GOOGLE = {
  ID: CLIENTE_ID,
  SECRET: CLIENTE_SECRET,
  REFRESH: CLIENT_REFRESH,
  REDIRECT: REDIRECT_URI,
  REFRESH_TOKEN: REFRESH_TOKEN,
};

// Export configurations
export { PORT, SECRET, MONGO_URL, CLOUDINARY, GOOGLE };
